### ISSUE TITLE
ParseError: not well-formed (invalid token)

### ISSUE THREAD

**Issue by mercs213** [eddie3/gogrepo#14]
Getting errors on certain games when trying to update them.

C:\Users\REMOVED USERNAME\Downloads\GOG Updates>gogrepo.py update -os windows -lang en -id starcrawlers
19:04:15 | loading local manifest...
19:04:15 | fetching game product data (page 1)...
19:04:16 | fetching game product data (page 2 / 16)...
19:04:17 | fetching game product data (page 3 / 16)...
19:04:17 | fetching game product data (page 4 / 16)...
19:04:18 | fetching game product data (page 5 / 16)...
19:04:18 | fetching game product data (page 6 / 16)...
19:04:19 | fetching game product data (page 7 / 16)...
19:04:20 | fetching game product data (page 8 / 16)...
19:04:20 | fetching game product data (page 9 / 16)...
19:04:21 | fetching game product data (page 10 / 16)...
19:04:22 | fetching game product data (page 11 / 16)...
19:04:22 | fetching game product data (page 12 / 16)...
19:04:23 | fetching game product data (page 13 / 16)...
19:04:23 | found "starcrawlers" in product data!
19:04:23 | (1 / 1) fetching game details for starcrawlers...
19:04:28 | error
Traceback (most recent call last):
  File "C:\Users\REMOVED USERNAME\Downloads\GOG Updates\gogrepo.py", line 647, in cmd_update
    filter_downloads(item.downloads, item_json_data['downloads'], lang_list, os_list)
  File "C:\Users\REMOVED USERNAME\Downloads\GOG Updates\gogrepo.py", line 347, in filter_downloads
    fetch_file_info(d, True)
  File "C:\Users\REMOVED USERNAME\Downloads\GOG Updates\gogrepo.py", line 309, in fetch_file_info
    shelf_etree = xml.etree.ElementTree.parse(page).getroot()
  File "C:\Program Files (x86)\Python\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\Program Files (x86)\Python\lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "C:\Program Files (x86)\Python\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Program Files (x86)\Python\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 128

**Comment by eddie3** [comment]
I fixed this yesterday, are you on the latest version of gogrepo.py?

Cheers

**Comment by mercs213** [comment]
Oops, just noticed you updated it yesterday. Long day today sorry lol. I was not on latest version Thanks!

**Comment by eddie3** [comment]
Not a problem, thanks for reporting!
