### ISSUE TITLE
login issue: TypeError: putch() argument 1 must be char, not unicode 

### ISSUE THREAD

**Issue by irate-overlord** [eddie3/gogrepo#24]
C:\{directory here}>gogrepo.py login
enter username: newellrp1@yahoo.com
11:35:03 | fatal...
Traceback (most recent call last):
  File "C:\{directory here}", line 1167, in <m
odule>
    main(process_argv(sys.argv))
  File "C:\{directory here}", line 1139, in ma
in
    cmd_login(args.username, args.password)
  File "C:\{directory here}", line 537, in cmd
_login
    login_data['passwd'] = getpass.getpass("enter password: ")
  File "C:\Python27\lib\getpass.py", line 95, in win_getpass
    msvcrt.putch(c)
TypeError: putch() argument 1 must be char, not unicode

I replaced my actual directory name with  {directory here}

**Comment by eddie3** [comment]
Fixed merged. Thanks @HamsterExAstris for the PR.
