### ISSUE TITLE
Parentheses in filenames are not decoded

### ISSUE THREAD

**Issue by Shiryou** [eddie3/gogrepo#31]
The parentheses in the filenames have been encoded and need to be decoded.

**Comment by JayB33** [comment]
I now get this when attempting to download.
```
Traceback (most recent call last):
  File "gogrepo.py", line 1167, in <module>
    main(process_argv(sys.argv))
  File "gogrepo.py", line 1147, in main
    cmd_download(args.savedir, args.skipextras, args.skipgames, args.skipids, args.dryrun, args.id)
  File "gogrepo.py", line 845, in cmd_download
    fd_info.write(html2text(item.changelog).strip())
  File "C:\Python27\lib\site-packages\html2text\__init__.py", line 937, in html2text
    return h.handle(html)
  File "C:\Python27\lib\site-packages\html2text\__init__.py", line 149, in handle
    self.feed(data)
  File "C:\Python27\lib\site-packages\html2text\__init__.py", line 146, in feed
    HTMLParser.HTMLParser.feed(self, data)
  File "C:\Python27\lib\HTMLParser.py", line 108, in feed
    self.goahead(0)
  File "C:\Python27\lib\HTMLParser.py", line 148, in goahead
    k = self.parse_starttag(i)
  File "C:\Python27\lib\HTMLParser.py", line 266, in parse_starttag
    % (rawdata[k:endpos][:20],))
  File "C:\Python27\lib\HTMLParser.py", line 115, in error
    raise HTMLParseError(message, self.getpos())
HTMLParseError: junk characters in start tag: u'\u201dBLUEPRINT_NAME\u201d>', at line 57, column 9
PS H:\gogrepo>
```

**Comment by Shiryou** [comment]
Your IP is generally only blocked for 24 hours if I remember correctly. If you haven't already, try running the download off your VPN again.

**Comment by JayB33** [comment]
The thing is I didn't do anything to warrant having my IP blocked. Gogrepo also freezes when fetching title data quite often, even when I successfully connect.
