### ISSUE TITLE
Game download randomly stops

### ISSUE THREAD

**Issue by BloodShed-Oni** [eddie3/gogrepo#44]
Single game download or complete library download will randomly just stop.
Restarting the script only fixes the problem until it randomly does it again.

**Comment by Wesley-Chan** [comment]
I think this problem comes from GOG's CDN. As opposed to Steam, who has servers all around all the continents, I think GOG's servers mainly reside in EU. When it's too crowded, it put speed limit on your session or even just drop you. I can experience the same behaviour with FireFox.

**Comment by MarioVilas** [comment]
Not sure if it's the same problem but I keep getting this assertion error, doesn't seem like a CDN problem...

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./gogrepo.py", line 927, in worker
    assert out.tell() == end + 1
AssertionError
```

**Comment by Wesley-Chan** [comment]
For as far as I can tell, the download size doesn't match what's on the metadata. Still sounds like a CDN problem.

I encountered this assertion quite often as well. I think the bigger problem is, the thread just died there and nothing did it do to retry. I suggest you make 30 threads and leave it on before you go to bed until the maintainer fix this.

**Comment by eddie3** [comment]
Thanks. This will be fixed.. definitely shouldn't just stop. It is indeed usually indicative of CDN-side problem however.

Does anyone know of specific games that currently show this?

**Comment by BloodShed-Oni** [comment]
Seems to be random.

I've had it with The Witcher 3 and the Bioshock games.
