### ISSUE TITLE
can't login anymore - "ValueError: unknown url type: 'None'"

### ISSUE THREAD

**Issue by nazgul6** [eddie3/gogrepo#75]
Anyone else seeing this preventing logging in or using the script?

> Traceback (most recent call last):
  File "/root/gog-script/gogrepo.py", line 1210, in <module>
    main(process_argv(sys.argv))
  File "/root/gog-script/gogrepo.py", line 1182, in main
    cmd_login(args.username, args.password)
  File "/root/gog-script/gogrepo.py", line 560, in cmd_login
    with request(login_data['auth_url'], delay=0) as page:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/gog-script/gogrepo.py", line 167, in request
    req = Request(url, data=enc_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 322, in __init__
    self.full_url = url
    ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 348, in full_url
    self._parse()
  File "/usr/lib/python3.11/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'None'

This is using Python 3.11.2. I also tried ToxiClay's version, which specifically claims as tested on Python 3.11.2 and I get the same output. 

Any help much appreciated! 

Thanks

**Comment by eddie3** [comment]
Thanks for raising this. I'll try to take a look soon

**Comment by Donione** [comment]
Hello,
I've just encountered this as well.
It seems that fetching the auth url fails to find any.
When I replaced `login_data['auth_url']` with 'login.gog.com/login' in the `fetch the login token` step I was prompted to enter the two-step security code. I've received it and entered it but the login still failed.
Since then when I try logging in, I'm not prompted to enter the security code anymore and the login fails.

I'm not sure if any of that is helpful in any way but I though I'll share my finding from a little bit of digging.

**Comment by Donione** [comment]
FYI, Kalanyr's version seems to be working fine. I haven't compared the login code to see if it's something obvious/trivial.

**Comment by ToxiClay** [comment]
> This is using Python 3.11.2. I also tried ToxiClay's version, which specifically claims as tested on Python 3.11.2 and I get the same output.

Yeah, this must be a change on GOG's back end that occurred well beyond my rewrite to support Python 3. I apologize if that came off as confusing, and I also appreciate the time taken to see if my fork worked. 🙏

**Comment by nazgul6** [comment]
Kalanyr's version indeed seems to work.

**Comment by ToxiClay** [comment]
> FYI, Kalanyr's version seems to be working fine. I haven't compared the login code to see if it's something obvious/trivial.

The login code in Kalanyr's version seems more complex, and also calls out to other functions that they'd written. More than that, there appears to have been a significant amount of refactoring and expansion (3991 LOC versus 1175 LOC), so backporting `cmd_login` feels like it'd be a challenge.

**Comment by eddie3** [comment]
Yeah sorry folks this will take time. I'd suggest you use one of the various forks for now. Sorry for the inconvenience.

**Comment by ToxiClay** [comment]
No, not at all! I can't speak for everyone, but I deeply appreciate the work you did to create this utility in the first place. Take the time you need!

**Comment by Donione** [comment]
I second what ToxiClay said. No worries and thank you for you work, @eddie3 !

**Comment by disi** [comment]
Mine broke sort of a week ago.

> Yeah sorry folks this will take time. I'd suggest you use one of the various forks for now. Sorry for the inconvenience.

I added pull request with a fixed working auth_url.
the cookie file, update, download etc., still works fine.
